server:
  port: 8081

app:
  backend-url: http://localhost:${server.port:8081}

spring:
  application:
    name: fido2-poc

entra-id:
  credential:
    client-id: ${ENTRA_CLIENT_ID}
    client-secret: ${ENTRA_CLIENT_SECRET}
    tenant-id: ${ENTRA_TENANT_ID}

